export const APPLICATIONS = 'APPLICATIONS';
export const PERFORMANCES = 'PERFORMANCES';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const APPMUNES = 'APPMUNES';
export const SERVICEDIFFERENCE = 'SERVICEDIFFERENCE';